name: Release
on:
  schedule:
    - cron: "0 5 3 * *"
  workflow_dispatch:
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Podman
        run: sudo apt update && sudo apt install podman qemu-user-static

      - name: Enable Multi-Arch Builds
        run: sudo podman run --rm --privileged docker.io/multiarch/qemu-user-static --reset -p yes

      - name: Log into GitHub Container Registry
        run: podman login ghcr.io --username ${{ github.repository_owner }} --password ${{ secrets.BLOOBOX_RELEASE_OPERATOR_GITHUB_PAT }}

      - name: Create Container Manifest
        run: podman manifest create ghcr.io/slib53/bloobox

      - name: Build Container Image
        run: podman build --jobs=2 --platform=linux/amd64,linux/arm64 --squash --manifest ghcr.io/slib53/bloobox .

      - name: Push Container Image
        run: podman manifest push ghcr.io/slib53/bloobox
