name: Rolling Release
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 1 * * 0"
  workflow_dispatch:
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Publish latest
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: ghcr.io/slib53/bloobox
          push: true

      - name: Publish terraform
        uses: docker/build-push-action@v2
        with:
          context: ./alt/terraform
          build-args: |
            TERRAFORM_ZIP_URL=https://releases.hashicorp.com/terraform/0.14.6/terraform_0.14.6_linux_amd64.zip
          tags: ghcr.io/slib53/bloobox:terraform
          push: true
