name: Rolling Release
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 1 * * 0"
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Publish Image
        uses: docker/build-push-action@v1
        with:
          username: $GITHUB_ACTOR
          password: ${{ secrets.CR_PAT }}
          registry: ghcr.io
          tags: latest
