name: Rolling Release
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 1 * * 0"
  workflow_dispatch:
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Build & Publish latest
        uses: docker/build-push-action@v2
        with:
          context: .
          build-args: |
            PEPPER_GIT_URL=${{ secrets.PEPPER_GIT_URL }}
          tags: ghcr.io/slib53/bloobox
          push: true
